psd6/urls.py
from django.urls import path, include
from . import views

app_name = "psd6"
urlpatterns = [
    path('create', views.createPSD, name="createPSD"),
    path('getData', views.getData, name="getData"),
    path('list', views.listPSD, name="listPSD"),
    path('deleteDaftarItem/<nomorPesanan>/<noUrut>/', views.deleteDaftarItem, name="deleteDaftarItem"),
    path('delete/<nomorPesanan>/', views.deletePSD, name="deletePSD"),
    path('update/<nomorPesanan>/', views.updatePSD, name="updatePSD"),
    path('detail/<nomorPesanan>/', views.detailPSD, name="detailPSD"),
    path('tambahDaftarItem', views.tambahDaftarItem, name="tambahDaftarItem")
]

tk4a11/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('PSD/', include('psd6.urls')),
    path('RiwayatStatusPSD/', include('riwayatStatusPSD7.urls')),
    path('StokFaskes/', include('stockFaskes8.urls')),
    path('faskes_5/', include('faskes_5.urls')),
    path('warehouseSatgas_5/', include('warehouseSatgas_5.urls')),
    path('batchPengiriman_5/', include('batchPengiriman_5.urls')),

]

warehouseSatgas_5/urls.py
from django.urls import path
from .views import ajaxidLokasiWarehouse, create_warehousesatgas, ajaxLokasiWarehouse,read_warehousesatgas, delete_warehousesatgas, update_warehousesatgas
app_name = 'warehouseSatgas_5'

urlpatterns = [
    path('createWarehouseSatgas/', create_warehousesatgas, name='createWarehouseSatgas'),
    path('ajaxidLokasiWarehouse/', ajaxidLokasiWarehouse, name='ajaxidLokasiWarehouse'),
    path('ajaxLokasiWarehouse/', ajaxLokasiWarehouse, name='ajaxLokasiWarehouse'),
    path('readWarehouseSatgas/', read_warehousesatgas, name='readWarehouseSatgas'),
    path('readWarehouseSatgasS/', read_warehousesatgas, name='readWarehouseSatgasS'),
    path('deleteWarehouseSatgas/', delete_warehousesatgas, name='deleteWarehouseSatgas'),
    path('updateWarehouseSatgas/', update_warehousesatgas, name='updateWarehouseSatgas'),
]

warehouseSatgas_5/models.py
from django.db import models

# Create your models here.

warehouseSatgas_5/forms.py
from django import forms
import datetime
from collections import namedtuple
from django.db import connection


class CreateWarehouseSatgasForm(forms.Form):
    provinsi_list = []
    provinsi = forms.ChoiceField(choices=provinsi_list, required=True)
    
    id_lokasi_list = []
    id_lokasi = forms.ChoiceField(choices=id_lokasi_list, required=True)
    
    lokasi = forms.CharField(label=("Lokasi"), required=True, max_length=50)


    def __init__(self, *args, **kwargs):
        super(CreateWarehouseSatgasForm, self).__init__(*args, **kwargs)
        with connection.cursor() as cursor:
            cursor.execute("SELECT DISTINCT PROVINSI, PROVINSI FROM SIDIA.LOKASI,SIDIA.WAREHOUSE_PROVINSI WHERE LOKASI.ID NOT IN (SELECT ID_LOKASI FROM SIDIA.WAREHOUSE_PROVINSI)")
            self.fields['provinsi'].choices = cursor.fetchall()
            cursor.execute("SELECT ID, ID FROM SIDIA.LOKASI")
            
            self.fields['provinsi'].widget.attrs = {'id': 'provinsi'}
            self.fields['id_lokasi'].widget.attrs = {'id': 'id_lokasi'}
            self.fields['lokasi'].widget.attrs = {'id': 'lokasi'}       

class UpdateWarehouseSatgasForm(forms.Form):
    provinsi = forms.CharField(label=("Provinsi"), required=True, max_length=50)

    id_lokasi_list = []
    id_lokasi = forms.ChoiceField(choices=id_lokasi_list, required=True)
   
    lokasi = forms.CharField(label=("Lokasi"), required=True, max_length=50)


    def __init__(self, *args, **kwargs):
        super(UpdateWarehouseSatgasForm, self).__init__(*args, **kwargs)
        with connection.cursor() as cursor:
            
            self.fields['provinsi'].widget.attrs = {'id': 'provinsi'}
            self.fields['id_lokasi'].widget.attrs = {'id': 'id_lokasi'}
            self.fields['lokasi'].widget.attrs = {'id': 'lokasi'}

warehouseSatgas_5/views.py
from django.shortcuts import render
from django.core import serializers
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import *
from django.db import connection
from datetime import datetime
from django.contrib import messages



def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def ajaxidLokasiWarehouse(request):
    provinsi = request.GET.get('provinsi')
    print(provinsi)
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT ID FROM SIDIA.LOKASI WHERE PROVINSI = %s AND LOKASI.ID NOT IN (SELECT ID_LOKASI FROM SIDIA.WAREHOUSE_PROVINSI)", [provinsi])
        data = cursor.fetchall()
    list_idLokasi = []
    for i in data:
        list_idLokasi.append(i[0])

    return JsonResponse({'id': list_idLokasi})


def ajaxLokasiWarehouse(request):
    id_lokasi = request.GET.get('id_lokasi')
    print(id_lokasi)
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT JALAN_NO,KELURAHAN,KECAMATAN,KABKOT,PROVINSI FROM SIDIA.LOKASI WHERE ID = %s", [id_lokasi])
        data = cursor.fetchall()
    list_lokasi = []
    for i in data[0]:
        list_lokasi.append(i)

    return JsonResponse({'id': list_lokasi})

def create_warehousesatgas(request):
    form = CreateWarehouseSatgasForm()
    if request.method == "POST":
        provinsi = request.POST['provinsi']
        id_lokasi = request.POST['id_lokasi']
        lokasi = request.POST['lokasi']
        
        data_baru = [id_lokasi]
        print(data_baru)
        with connection.cursor() as cursor:
            cursor.execute(
                'INSERT INTO SIDIA.WAREHOUSE_PROVINSI VALUES (%s)', data_baru)
            cursor.execute("SET SEARCH_PATH TO SIDIA;")
            sql = "SELECT DISTINCT JALAN_NO,KELURAHAN,KECAMATAN,KABKOT,PROVINSI from SIDIA.LOKASI,SIDIA.WAREHOUSE_PROVINSI WHERE ID = ID_LOKASI;"
            cursor.execute(sql)
            result = dictfetchall(cursor)
            return render(request, 'readWarehouseSatgas.html', {'form': result})       
    return render(request, 'createWarehouseSatgas.html', {'form': form})

def read_warehousesatgas(request):
        role = request.session['role']
        if role == "admin_satgas":
            with connection.cursor() as cursor:
                cursor.execute("SET SEARCH_PATH TO SIDIA;")
                sql = "SELECT DISTINCT JALAN_NO,KELURAHAN,KECAMATAN,KABKOT,PROVINSI from SIDIA.LOKASI,SIDIA.WAREHOUSE_PROVINSI WHERE ID = ID_LOKASI;"
                cursor.execute(sql)
                result = dictfetchall(cursor)
            return render(request, 'readWarehouseSatgas.html', {'form': result})

            
        elif role == "supplier":
            with connection.cursor() as cursor:
                cursor.execute("SET SEARCH_PATH TO SIDIA;")
                sql = "SELECT DISTINCT JALAN_NO,KELURAHAN,KECAMATAN,KABKOT,PROVINSI from SIDIA.LOKASI,SIDIA.WAREHOUSE_PROVINSI WHERE ID = ID_LOKASI;"
                cursor.execute(sql)
                result = dictfetchall(cursor)
            return render(request, 'readWarehouseSatgasS.html', {'form': result})
        else:
            pass

def delete_warehousesatgas(request):
    if request.method == 'GET':
        if request.GET.get('provinsi') is not None and request.GET.get('kabkot') is not None and request.GET.get('kecamatan') is not None and request.GET.get('kelurahan') is not None and request.GET.get('jalan_no') is not None :
            provinsi = request.GET.get('provinsi')
            kabkot = request.GET.get('kabkot')
            kecamatan = request.GET.get('kecamatan')
            kelurahan = request.GET.get('kelurahan')
            jalan_no = request.GET.get('jalan_no')

            with connection.cursor() as cursor:
                cursor.execute("DELETE FROM SIDIA.WAREHOUSE_PROVINSI WHERE ID_LOKASI IN (SELECT ID FROM SIDIA.LOKASI JOIN SIDIA.WAREHOUSE_PROVINSI ON ID = ID_LOKASI WHERE PROVINSI = %s AND KABKOT = %s AND KECAMATAN = %s AND KELURAHAN = %s AND JALAN_NO = %s)", [provinsi,kabkot,kecamatan,kelurahan,jalan_no])
                messages.success(request, ('Data berhasil dihapus'))

    return HttpResponseRedirect(reverse('warehouseSatgas_5:readWarehouseSatgas'))

def update_warehousesatgas(request):

    if request.method == 'GET':
        print(request.GET.get('provinsi'))

        if request.GET.get('provinsi') is not None:
            provinsi = request.GET.get('provinsi')

            with connection.cursor() as cursor:
                cursor.execute("SELECT ID,JALAN_NO,PROVINSI,KABKOT,KECAMATAN,KELURAHAN FROM SIDIA.LOKASI WHERE ID IN (SELECT ID_LOKASI FROM SIDIA.WAREHOUSE_PROVINSI) AND PROVINSI = %s", [provinsi])
                result = dictfetchall(cursor)

            data_warehouse = {}
            data_warehouse['id_lokasi'] = result[0]['id']
            data_warehouse['provinsi'] = result[0]['provinsi']
            data_warehouse['lokasi'] = result[0]['jalan_no'],result[0]['kecamatan'], result[0]['kelurahan'],result[0]['kabkot']
            form = UpdateWarehouseSatgasForm(initial=data_warehouse)
    
    else:
        id_lokasi = request.POST['id_lokasi']
        provinsi = request.POST['provinsi']
        lokasi = request.POST['lokasi']

        data_update = [id_lokasi,provinsi]
        with connection.cursor() as cursor:
            cursor.execute("UPDATE SIDIA.WAREHOUSE_PROVINSI SET id_lokasi = %s WHERE id_lokasi IN (select id FROM SIDIA.LOKASI WHERE provinsi=%s)", data_update)        
        return redirect('warehouseSatgas_5:readWarehouseSatgas')
    return render(request, 'updateWarehouseSatgas.html', {'form': form})

warehouseSatgas_5/templates/createWarehouseSatgas.html
{% extends "base_template.html" %}

{% block content %}

<style>
    input, select {
        display: block;
        width: 50%;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        color: #555;
        background-color: #fff;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
    }
</style>
<div class="container">  
{% if request.session.role == 'admin_satgas' %} 
    <h1 class="display-4">Form Tambah Warehouse Satgas</h1>
    <small class="text-muted">{{ message }}</small> <br><br> 
<hr class="my-4">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-outline-primary" type="submit">Simpan</button>
    </form>
{% else %}
        <h3>Harus Login dahulu sebagai Admin Satgas</h3>
        <a href="{% url 'login' %}">
            <button>
                Login!
            </button>
        </a>
{% endif %}
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
   $(document).ready(function () {
        
        $.ajax({
            type: 'GET',
            url: "{% url 'warehouseSatgas_5:ajaxLokasiWarehouse' %}",
            data: {
                id_lokasi: $('#id_lokasi').val()
            },
            async: false,
            success: function (response) {
                let res=''
                response.id.map((e) => {
                    res += e + ' , ';
                })
                $('#lokasi').val(res)
                $('#lokasi').prop('readonly',true)

            }
        });

        $.ajax({
            type: 'GET',
            url: "{% url 'warehouseSatgas_5:ajaxidLokasiWarehouse' %}",
            data: {
                provinsi: $('#provinsi').val()
            },
            async: false,
            success: function (response) {
                response.id.map((e) => {
                    $('#id_lokasi').append(new Option(e, e))
                })
            }
        });
        

        $('#provinsi').on('change', function () {
            $('#id_lokasi').find('option').remove()
            $.ajax({
                type: 'GET',
                url: "{% url 'warehouseSatgas_5:ajaxidLokasiWarehouse' %}",
                data: {
                    provinsi: $('#provinsi').val()
                },
                async: false,
                success: function (response) {
                    response.id.map((e) => {
                        $('#id_lokasi').append(new Option(e, e))
                    })
                }
            });

            $('#lokasi').find('option').remove()
            $.ajax({
                type: 'GET',
                url: "{% url 'warehouseSatgas_5:ajaxLokasiWarehouse' %}",
                data: {
                    provinsi: $('#provinsi').val(),
                    id_lokasi: $('#id_lokasi').val()
                },
                async: false,
                success: function (response) {
                    let res=''
                    response.id.map((e) => {
                        res += e + ' , ';
                    })
                    $('#lokasi').val(res)
                    $('#lokasi').prop('readonly',true)

                }
            });

            $('#id_lokasi').on('change', function () {
                $('#lokasi').val('')
                $.ajax({
                    type: 'GET',
                    url: "{% url 'warehouseSatgas_5:ajaxLokasiWarehouse' %}",
                    data: {
                        id_lokasi: $('#id_lokasi').val()
                    },
                    async: false,
                    success: function (response) {
                        let res=''
                        response.id.map((e) => {
                        res += e + ' , ';
                        })
                        $('#lokasi').val(res)
                        $('#lokasi').prop('readonly',true)

                    }
                });
            });

            
           
        
        });
    });
</script>
{% endblock content %}

warehouseSatgas_5/templates/readWarehouseSatgas.html
{% extends "base_template.html" %}
{% block content %}

<style>
    input, select {
        display: block;
        width: 50%;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        color: #555;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
    }
</style>

<div class="container col-lg-12">  
  <h1 class="display-4">List Warehouse Satgas</h1>
  <hr class="my-4">
  <div class=col-lg-12>
      <table class="table table-striped table table-hover" style="text-align: center;"> 
          <thead>

              <tr style="text-align: center;">
                <th scope="col">No</th>
                <th scope="col">Provinsi</th>
                <th scope="col">Lokasi</th>
                
              </tr>
          </thead>

          <tbody>
            {% for item in form %}
            <tr>
              <td>{{ forloop.counter}}</td>
              <td>{{ item.provinsi}}</td>
              <td>{{ item.jalan_no}} {{ item.kelurahan}} {{ item.kecamatan}} {{ item.kabkot}}</td>
              

                <td>
                  <form action="{% url 'warehouseSatgas_5:updateWarehouseSatgas' %}" method="get">
                      <input type="hidden" id="provinsi" name="provinsi" value="{{ item.provinsi }}">
                      <button type="submit" id="tombolupdate" class="btn btn-outline-primary">Update</button>
                  </form>
                </td>
                <td>
                  <form action="{% url 'warehouseSatgas_5:deleteWarehouseSatgas' %}" method="get">
                      <input type="hidden" id="provinsi" name="provinsi" value="{{ item.provinsi }}">
                      <input type="hidden" id="kecamatan" name="kecamatan" value="{{ item.kecamatan }}">
                      <input type="hidden" id="kabkot" name="kabkot" value="{{ item.kabkot }}">
                      <input type="hidden" id="kelurahan" name="kelurahan" value="{{ item.kelurahan }}">
                      <input type="hidden" id="jalan_no" name="jalan_no" value="{{ item.jalan_no }}">
                      <button type="submit" id="tomboldelete" class="btn btn-outline-primary">Delete</button>
                  </form>
                </td>
            </tr>
            {% endfor %}
      
          </tbody>
      </table>
      {% if messages %}
        <div>
            {% for message in messages %}
                <h5 class="{{message.tag}}">{{ message.message }}</h5>
            {% endfor %}
        </div>
      {% endif %}
  </div>
  </div>

</div>
{% endblock content %}

warehouseSatgas_5/templates/readWarehouseSatgasS.html
{% extends "base_template.html" %}
{% block content %}

<style>
    input, select {
        display: block;
        width: 50%;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        color: #555;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
    }
</style>

<div class="container col-lg-12">  
  <h1 class="display-4">List Warehouse Satgas</h1>
  <hr class="my-4">
  <div class=col-lg-12>
      <table class="table table-striped table table-hover" style="text-align: center;"> 
          <thead>

              <tr style="text-align: center;">
                <th scope="col">No</th>
                <th scope="col">Provinsi</th>
                <th scope="col">Lokasi</th>
                
                
              </tr>
          </thead>

          <tbody>
            {% for item in form %}
            <tr>
              <td>{{ forloop.counter}}</td>
              <td>{{ item.provinsi}}</td>
              <td>{{ item.jalan_no}} {{ item.kelurahan}} {{ item.kecamatan}} {{ item.kabkot}}</td>
              

               
            </tr>
            {% endfor %}
      
          </tbody>
      </table>
      {% if messages %}
        <div>
            {% for message in messages %}
                <h5 class="{{message.tag}}">{{ message.message }}</h5>
            {% endfor %}
        </div>
      {% endif %}
  </div>
  </div>

</div>
{% endblock content %}

warehouseSatgas_5/templates/updateWarehouseSatgas.html
{% extends "base_template.html" %}

{% block content %}

<style>
    input, select {
        display: block;
        width: 50%;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        color: #555;
        background-color: #fff;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
    }
</style>
<div class="container">  
    <h1 class="display-4">Form Ubah Warehouse Satgas</h1>
    <small class="text-muted">{{ message }}</small> <br><br> 
<hr class="my-4">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-outline-primary" type="submit">Simpan</button>
    </form>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
   $(document).ready(function () {
        

        $.ajax({
            type: 'GET',
            url: "{% url 'warehouseSatgas_5:ajaxidLokasiWarehouse' %}",
            data: {
                provinsi: $('#provinsi').val()
            },
            async: false,
            success: function (response) {
                response.id.map((e) => {
                    $('#id_lokasi').append(new Option(e, e))
                })
            }
        });
        
        $('#lokasi').val('')
        $.ajax({
            type: 'GET',
            url: "{% url 'warehouseSatgas_5:ajaxLokasiWarehouse' %}",
            data: {
                id_lokasi: $('#id_lokasi').val()
            },
            async: false,
            success: function (response) {
                let res=''
                response.id.map((e) => {
                    res += e + ' , ';
                })
                $('#lokasi').val(res)
                $('#lokasi').prop('readonly',true)

            }
        });

        $('#id_lokasi').on('change', function () {
            $('#lokasi').val('')
            $.ajax({
                type: 'GET',
                url: "{% url 'warehouseSatgas_5:ajaxLokasiWarehouse' %}",
                data: {
                    id_lokasi: $('#id_lokasi').val()
                },
                async: false,
                success: function (response) {
                    let res=''
                    response.id.map((e) => {
                    res += e + ' , ';
                    })
                    $('#lokasi').val(res)
                    $('#lokasi').prop('readonly',true)

                }
            });
        });
    

        $('#provinsi').on('change', function () {
            $('#id_lokasi').find('option').remove()
            $.ajax({
                type: 'GET',
                url: "{% url 'warehouseSatgas_5:ajaxidLokasiWarehouse' %}",
                data: {
                    provinsi: $('#provinsi').val()
                },
                async: false,
                success: function (response) {
                    response.id.map((e) => {
                        $('#id_lokasi').append(new Option(e, e))
                    })
                }
            });

            $('#lokasi').val('')
            $.ajax({
                type: 'GET',
                url: "{% url 'warehouseSatgas_5:ajaxLokasiWarehouse' %}",
                data: {
                    provinsi: $('#provinsi').val(),
                    id_lokasi: $('#id_lokasi').val()
                },
                async: false,
                success: function (response) {
                    let res=''
                    response.id.map((e) => {
                        res += e + ' , ';
                    })
                    $('#lokasi').val(res)
                    $('#lokasi').prop('readonly',true)

                }
            });

            $('#id_lokasi').on('change', function () {
                $('#lokasi').val('')
                $.ajax({
                    type: 'GET',
                    url: "{% url 'warehouseSatgas_5:ajaxLokasiWarehouse' %}",
                    data: {
                        id_lokasi: $('#id_lokasi').val()
                    },
                    async: false,
                    success: function (response) {
                        let res=''
                        response.id.map((e) => {
                        res += e + ' , ';
                        })
                        $('#lokasi').val(res)
                        $('#lokasi').prop('readonly',true)

                    }
                });
            });

            $('#provinsi').prop('readonly',true)

           
        
        });
    });
</script>
{% endblock content %}