batchPengiriman_5/urls.py
from django.urls import path
from .views import create_batchpengiriman
app_name = 'batchPengiriman_5'

urlpatterns = [
    path('createBatchPengiriman/', create_batchpengiriman, name='createBatchPengiriman'),
    

]

faskes_5/urls.py
from django.urls import path
from .views import create_faskes, ajaxLokasiFaskes, ajaxTipeFaskes, read_faskes, delete_faskes, update_faskes
app_name = 'faskes_5'

urlpatterns = [
    path('createFaskes/', create_faskes, name='createFaskes'),
    path('ajaxLokasiFaskes/', ajaxLokasiFaskes, name='ajaxLokasiFaskes'),
    path('ajaxTipeFaskes/', ajaxTipeFaskes, name='ajaxTipeFaskes'),
    path('readFaskes/', read_faskes, name='readFaskes'),
    path('readFaskesS/', read_faskes, name='readFaskesS'),
    path('deleteFaskes/', delete_faskes, name='deleteFaskes'),
    path('updateFaskes/', update_faskes, name='updateFaskes'),

]

login/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.home, name="home"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),
    path('registerPilihan', views.registerPilihan, name="registerPilihan"),
    path('regadminsatgas', views.register_adminsatgas, name="regadminsatgas"),
    path('regsupplier', views.register_supplier, name="regsupplier"),
    path('regpetugasdistribusi', views.register_petugasdistribusi, name="regpetugasdistribusi"),
    path('regpetugasfaskes', views.register_petugasfaskes, name="regpetugasfaskes"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('profile', views.profile, name='profile'),
]

psd6/urls.py
from django.urls import path, include
from . import views

app_name = "psd6"
urlpatterns = [
    path('create', views.createPSD, name="createPSD"),
    path('getData', views.getData, name="getData"),
    path('list', views.listPSD, name="listPSD"),
    path('deleteDaftarItem/<nomorPesanan>/<noUrut>/', views.deleteDaftarItem, name="deleteDaftarItem"),
    path('delete/<nomorPesanan>/', views.deletePSD, name="deletePSD"),
    path('update/<nomorPesanan>/', views.updatePSD, name="updatePSD"),
    path('detail/<nomorPesanan>/', views.detailPSD, name="detailPSD"),
    path('tambahDaftarItem', views.tambahDaftarItem, name="tambahDaftarItem")
]

tk4a11/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('PSD/', include('psd6.urls')),
    path('RiwayatStatusPSD/', include('riwayatStatusPSD7.urls')),
    path('StokFaskes/', include('stockFaskes8.urls')),
    path('faskes_5/', include('faskes_5.urls')),
    path('warehouseSatgas_5/', include('warehouseSatgas_5.urls')),
    path('batchPengiriman_5/', include('batchPengiriman_5.urls')),

]

warehouseSatgas_5/urls.py
from django.urls import path
from .views import ajaxidLokasiWarehouse, create_warehousesatgas, ajaxLokasiWarehouse,read_warehousesatgas, delete_warehousesatgas, update_warehousesatgas
app_name = 'warehouseSatgas_5'

urlpatterns = [
    path('createWarehouseSatgas/', create_warehousesatgas, name='createWarehouseSatgas'),
    path('ajaxidLokasiWarehouse/', ajaxidLokasiWarehouse, name='ajaxidLokasiWarehouse'),
    path('ajaxLokasiWarehouse/', ajaxLokasiWarehouse, name='ajaxLokasiWarehouse'),
    path('readWarehouseSatgas/', read_warehousesatgas, name='readWarehouseSatgas'),
    path('readWarehouseSatgasS/', read_warehousesatgas, name='readWarehouseSatgasS'),
    path('deleteWarehouseSatgas/', delete_warehousesatgas, name='deleteWarehouseSatgas'),
    path('updateWarehouseSatgas/', update_warehousesatgas, name='updateWarehouseSatgas'),
]

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms
import datetime
from collections import namedtuple
from django.db import connection

provinsiChoices = [
    ('Aceh','Aceh'),
    ('Sumatera Utara','Sumatera Utara'),
    ('Sumatera Barat','Sumatera Barat'),
    ('Riau','Riau'),
    ('Jambi','Jambi'),
    ('Sumatera Selatan','Sumatera Selatan'),
    ('Bengkulu','Bengkulu'),
    ('Lampung','Lampung'),
    ('Kepulauan Bangka Belitung','Kepulauan Bangka Belitung'),
    ('Kepulauan Riau','Kepulauan Riau'),
    ('DKI Jakarta','DKI Jakarta'),
    ('Jawa Barat','Jawa Barat'),
    ('Jawa Tengah','Jawa Tengah'),
    ('DI Yogyakarta','DI Yogyakarta'),
    ('Jawa Timur','Jawa Timur'),
    ('Banten','Banten'),
    ('Bali','Bali'),
    ('Nusa Tenggara Barat','Nusa Tenggara Barat'),
    ('Nusa Tenggara Timur','Nusa Tenggara Timur'),
    ('Kalimantan Barat','Kalimantan Barat'),
    ('Kalimantan Tengah','Kalimantan Tengah'),
    ('Kalimantan Selatan','Kalimantan Selatan'),
    ('Kalimantan Timur','Kalimantan Timur'),
    ('Kalimantan Utara','Kalimantan Utara'),
    ('Sulawesi Utara','Sulawesi Utara'),
    ('Sulawesi Tengah','Sulawesi Tengah'),
    ('Sulawesi Selatan','Sulawesi Selatan'),
    ('Sulawesi Tenggara','Sulawesi Tenggara'),
    ('Gorontalo','Gorontalo'),
    ('Sulawesi Barat','Sulawesi Barat'),
    ('Maluku','Maluku'),
    ('Maluku Utara','Maluku Utara'),
    ('Papua','Papua'),
    ('Papua Barat','Papua Barat')
]

class LoginForm(forms.Form):
    username = forms.CharField(label='Username:', max_length=50)
    password = forms.CharField(label='Password:', max_length=128)


class RegAdminSatgas(forms.Form):
    username = forms.CharField(label='Username', max_length=50)
    password = forms.CharField(label='Password', max_length=128)
    nama = forms.CharField(label='Nama', max_length=50)
    kelurahan = forms.CharField(label='Kelurahan', max_length=50)
    kecamatan = forms.CharField(label='Kecamatan', max_length=50)
    kabupatankota = forms.CharField(label='Kabupatan/Kota', max_length=50)
    provinsi = forms.ChoiceField(choices = provinsiChoices) 
    no_telp = forms.CharField(label='No Telepon', max_length=20)


class RegSupplier(forms.Form):
    organisasi = forms.CharField(label='Nama organisasi', max_length=50) 
    username = forms.CharField(label='Username', max_length=50)
    password = forms.CharField(label='Password', max_length=128)
    nama = forms.CharField(label='Nama', max_length=50)
    kelurahan = forms.CharField(label='Kelurahan', max_length=50)
    kecamatan = forms.CharField(label='Kecamatan', max_length=50)
    kabupatankota = forms.CharField(label='Kabupatan/Kota', max_length=50)
    provinsi = forms.ChoiceField(choices = provinsiChoices) 
    no_telp = forms.CharField(label='No Telepon', max_length=20)

class RegPetugasDistribusi(forms.Form):
    username = forms.CharField(label='Username', max_length=50)
    password = forms.CharField(label='Password', max_length=128)
    nama = forms.CharField(label='Nama', max_length=50)
    kelurahan = forms.CharField(label='Kelurahan', max_length=50)
    kecamatan = forms.CharField(label='Kecamatan', max_length=50)
    kabupatankota = forms.CharField(label='Kabupatan/Kota', max_length=50)
    provinsi = forms.ChoiceField(choices = provinsiChoices) 
    no_telp = forms.CharField(label='No Telepon', max_length=20)
    no_sim = forms.CharField(label='No SIM', max_length=20)


class RegPetugasFaskes(forms.Form):
    username = forms.CharField(label='Username', max_length=50)
    password = forms.CharField(label='Password', max_length=128)
    nama = forms.CharField(label='Nama', max_length=50)
    kelurahan = forms.CharField(label='Kelurahan', max_length=50)
    kecamatan = forms.CharField(label='Kecamatan', max_length=50)
    kabupatankota = forms.CharField(label='Kabupatan/Kota', max_length=50)
    provinsi = forms.ChoiceField(choices = provinsiChoices) 
    no_telp = forms.CharField(label='No Telepon', max_length=20)

login/views.py
from django.shortcuts import render
from django.shortcuts import render, reverse, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db import connection
from collections import namedtuple
from django.http import HttpResponse, JsonResponse
from .forms import LoginForm, RegAdminSatgas, RegSupplier, RegPetugasDistribusi, RegPetugasFaskes

    
def home(request):
    return render(request, "home.html")
    
def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def login(request) :
    message = ''
    if request.method =='POST':
        username = request.POST.get("username")
        password = request.POST.get("password")

        cursor = connection.cursor()

        sql = "select username, password from sidia.pengguna where username = " + "'" + username + "'" 
        cursor.execute(sql)
        auth = cursor.fetchone()
        print(auth)
            
        message = 'Invalid username or password'
        if auth != None:
            if password == auth[1]:
                request.session['username'] = username
                if search_role(username, 'admin_satgas'):
                    request.session['role'] = 'admin_satgas'
                elif search_role(username, 'supplier'):
                    request.session['role'] = 'supplier'
                elif search_role(username, 'petugas_distribusi'):
                    request.session['role'] = 'petugas_distribusi'
                elif search_role(username, 'petugas_faskes'):
                    request.session['role'] = 'petugas_faskes'
                print(request.session['username'])
                print(request.session['role'])
                return redirect('/dashboard')
            
    form = LoginForm()
    args = {'form': form, 'message' : message }
    return render(request, 'login.html', args)

def dashboard(request):
    try:
        username = request.session['username']
        role = request.session['role']

        if role == "admin_satgas":
           return render(request, "dashboardAS.html")
        elif role == "petugas_distribusi":
           return render(request, "dashboardPD.html")
        elif role == "petugas_faskes":
           return render(request, "dashboardPF.html")
        elif role == "supplier":
           return render(request, "dashboardS.html")
        else:
            return redirect('/')
    except:
            return redirect('/')

def search_role(username, role):
    cursor = connection.cursor()
    sql = "select * from sidia."+ role + " where username ='" + username + "';"
    cursor.execute(sql)
    sql_role = namedtuplefetchall(cursor)
    if len(sql_role) == 0:
            return False
    else:
            return True

def logout(request):
     try:
          del request.session['username']
          del request.session['role']
          print("log out success")
          return redirect('/')
     except:
          pass
     return redirect('/')

def registerPilihan(request):
    return render(request, "registerPilihan.html")

def register_adminsatgas(request):
    message = ' '
    success = "False"
    role = "admin_satgas"
    if request.method =='POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        nama = request.POST.get("nama")
        kelurahan = request.POST.get("kelurahan")
        kecamatan = request.POST.get("kecamatan")
        kabupatankota = request.POST.get("kabupatankota")
        provinsi = request.POST.get("provinsi")
        no_telp = request.POST.get("no_telp")
        

        cursor = connection.cursor()

        sql_count_pengguna = "select count(*) from sidia.pengguna where username = " + "'" + username + "'" 
        cursor.execute(sql_count_pengguna)
        count_pengguna = cursor.fetchone()

        sql_count_admin = "select count(*) from sidia.admin_satgas where username = " + "'" + username + "'" 
        cursor.execute(sql_count_admin)
        count_admin = cursor.fetchone()
        
        if count_pengguna[0] == 0 and count_admin[0] == 0 :
                sql_pengguna = "insert into sidia.pengguna VALUES (%s, %s, %s, %s, %s, %s, %s, %s);"
                cursor.execute(sql_pengguna,(username, password, nama, kelurahan, kecamatan, kabupatankota, provinsi , no_telp))

                sql_admin = "insert into sidia.admin_satgas VALUES ('" + username + "');"
                cursor.execute(sql_admin)
                message = 'Pendaftaran sebagai ' + role + ' berhasil dilakukan'
                success = "True"
                return redirect('login')

        else: 
            success = "False"
            message = 'Username tersebut sudah terdaftar dengan peran ' + role

    form = RegAdminSatgas()
    args = {'form': form, 'message' : message, 'success': success, 'role' : role}
    return render(request, 'register.html', args)


def register_supplier(request):
    message = ' '
    success = "False"
    role = "supplier"
    if request.method =='POST':
        organisasi = request.POST.get("organisasi")
        username = request.POST.get("username")
        password = request.POST.get("password")
        nama = request.POST.get("nama")
        kelurahan = request.POST.get("kelurahan")
        kecamatan = request.POST.get("kecamatan")
        kabupatankota = request.POST.get("kabupatankota")
        provinsi = request.POST.get("provinsi")
        no_telp = request.POST.get("no_telp")
        

        cursor = connection.cursor()

        sql_count_pengguna = "select count(*) from sidia.pengguna where username = " + "'" + username + "'" 
        cursor.execute(sql_count_pengguna)
        count_pengguna = cursor.fetchone()

        sql_count_supplier = "select count(*) from sidia.supplier where username = " + "'" + username + "'" 
        cursor.execute(sql_count_supplier)
        count_supplier = cursor.fetchone()
        

        if count_pengguna[0] == 0 and count_supplier[0] == 0 :
            sql_pengguna = "insert into sidia.pengguna VALUES (%s, %s, %s, %s, %s, %s, %s, %s);"
            cursor.execute(sql_pengguna,(username, password, nama, kelurahan, kecamatan, kabupatankota, provinsi , no_telp))

            sql_supplier = "insert into sidia.supplier VALUES ('" + username + "', '" + organisasi + "');"
            cursor.execute(sql_supplier)
            return redirect('login')
        else: 
            success = "False"
            message = 'Username tersebut sudah terdaftar dengan peran ' + role

    form = RegSupplier()
    args = {'form': form, 'message' : message, 'success': success, 'role' : role}
    return render(request, 'register.html', args)

def register_petugasdistribusi(request):
    message = ' '
    success = "False"
    role = "petugas_distribusi"
    if request.method =='POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        nama = request.POST.get("nama")
        kelurahan = request.POST.get("kelurahan")
        kecamatan = request.POST.get("kecamatan")
        kabupatankota = request.POST.get("kabupatankota")
        provinsi = request.POST.get("provinsi")
        no_telp = request.POST.get("no_telp")
        no_sim = request.POST.get("no_sim")
        

        cursor = connection.cursor()

        sql_count_pengguna = "select count(*) from sidia.pengguna where username = " + "'" + username + "'" 
        cursor.execute(sql_count_pengguna)
        count_pengguna = cursor.fetchone()

        sql_count_dist = "select count(*) from sidia.petugas_distribusi where username = " + "'" + username + "'" 
        cursor.execute(sql_count_dist)
        count_dist = cursor.fetchone()
    

        if count_pengguna[0] == 0 and count_dist[0] == 0 :
            sql_pengguna = "insert into sidia.pengguna VALUES (%s, %s, %s, %s, %s, %s, %s, %s);"
            cursor.execute(sql_pengguna,(username, password, nama, kelurahan, kecamatan, kabupatankota, provinsi , no_telp))

            sql_count_dist = "insert into sidia.petugas_distribusi VALUES ('" + username + "', '" + no_sim + "');"
            cursor.execute(sql_count_dist)
            return redirect('login')
        else: 
            success = "False"
            message = 'Username tersebut sudah terdaftar dengan peran ' + role

    form = RegPetugasDistribusi()
    args = {'form': form, 'message' : message, 'success': success, 'role' : role}
    return render(request, 'register.html', args)

def register_petugasfaskes(request):
    message = ' '
    role = "petugas_faskes"
    success = "False"
    if request.method =='POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        nama = request.POST.get("nama")
        kelurahan = request.POST.get("kelurahan")
        kecamatan = request.POST.get("kecamatan")
        kabupatankota = request.POST.get("kabupatankota")
        provinsi = request.POST.get("provinsi")
        no_telp = request.POST.get("no_telp")

        cursor = connection.cursor()

        sql_count_pengguna = "select count(*) from sidia.pengguna where username = " + "'" + username + "'" 
        cursor.execute(sql_count_pengguna)
        count_pengguna = cursor.fetchone()

        sql_count_petfaskes = "select count(*) from sidia.petugas_faskes where username = " + "'" + username + "'" 
        cursor.execute(sql_count_petfaskes)
        count_petfaskes = cursor.fetchone()
        

        if count_pengguna[0] == 0 and count_petfaskes[0] == 0 :
            sql_pengguna = "insert into sidia.pengguna VALUES (%s, %s, %s, %s, %s, %s, %s, %s);"
            cursor.execute(sql_pengguna,(username, password, nama, kelurahan, kecamatan, kabupatankota, provinsi , no_telp))

            sql_count_petfaskes = "insert into sidia.petugas_faskes VALUES ('" + username + "');"

login/templates/dashboardAS.html
{% extends "base_template.html" %}

{% block content %}

<div class="container col-lg-12">
    <h1 class="display-4">Homepage Admin Satgas</h1>
<p class="lead font-italic">SIDIA Indonesia</p>
<hr class="my-4">

<p class="h5">Profil:</p>
<a href="{% url 'profile' %}" class="btn btn-outline-primary" role="button">Profil Saya</a>
<a href="{% url 'logout' %}" class="btn btn-outline-primary" role="button">Logout</a>

<br><br><br>

<p class="h5">Permohonan Sumber Daya</p>
<a href="#" class="btn btn-outline-primary" role="button">Buat Permohonan Sumber Daya</a>
<a href="#" class="btn btn-outline-primary" role="button">List Permohonan Sumber Daya</a>
<a href="#" class="btn btn-outline-primary" role="button">List Riwayat Status Permohonan Sumber Daya</a>


<br><br><br>

<p class="h5">Item Sumber Daya</p>
<a href="#" class="btn btn-outline-primary" role="button">List Item Sumber Daya</a>

<br><br><br>

<p class="h5">Pesanan Sumber Daya</p>
<a href="{% url 'psd6:createPSD' %}" class="btn btn-outline-primary" role="button">Buat Pesanan Sumber Daya</a>
<a href="{% url 'psd6:listPSD' %}" class="btn btn-outline-primary" role="button">List Pesanan Sumber Daya</a>

<br><br><br>

<p class="h5">Kendaraan</p>
<a href="#" class="btn btn-outline-primary" role="button">Buat Kendataan</a>
<a href="#" class="btn btn-outline-primary" role="button">List Kendaraan</a>

<br><br><br>

<p class="h5">Batch Pengiriman</p>
<a href="{% url 'batchPengiriman_5:createBatchPengiriman' %}" class="btn btn-outline-primary" role="button">Buat Batch Pengiriman</a>
<a href="#" class="btn btn-outline-primary" role="button">List Batch Pengiriman</a>
<a href="#" class="btn btn-outline-primary" role="button">Buat Riwayat Status Batch Pengiriman</a>
<a href="#" class="btn btn-outline-primary" role="button">List Riwayat Status Batch Pengiriman</a>

<br><br><br>

<p class="h5">Lokasi</p>
<a href="#" class="btn btn-outline-primary" role="button">Buat Lokasi</a>
<a href="#" class="btn btn-outline-primary" role="button">List Lokasi</a>

<br><br><br>

<p class="h5">Fasilitas Kesehatan</p>
<a href="{% url 'faskes_5:createFaskes' %}" class="btn btn-outline-primary" role="button">Buat Fasilitas Kesehatan</a>
<a href="{% url 'faskes_5:readFaskes' %}" class="btn btn-outline-primary" role="button">List Fasilitas Kesehatan</a>
<a href="{% url 'createStokFaskes' %}" class="btn btn-outline-primary" role="button">Buat Stok Fasilitas Kesehatan</a>
<a href="{% url 'listStokFaskes' %}" class="btn btn-outline-primary" role="button">List Stok Fasilitas Kesehatan</a>

<br><br><br>

<p class="h5">Warehouse Satgas</p>
<a href="{% url 'warehouseSatgas_5:createWarehouseSatgas' %}" class="btn btn-outline-primary" role="button">Buat Warehouse Satgas</a>
<a href="{% url 'warehouseSatgas_5:readWarehouseSatgas' %}" class="btn btn-outline-primary" role="button">List Warehouse Satgas</a>
<a href="#" class="btn btn-outline-primary" role="button">Buat Stok Warehouse Satgas</a>
<a href="#" class="btn btn-outline-primary" role="button">List Stok Warehouse Satgas</a>

</div>
{% endblock content %}

login/templates/dashboardPD.html
{% extends "base_template.html" %}

{% block content %}

<h1 class="display-4">Homepage Petugas Distribusi</h1>
<p class="lead font-italic">SIDIA Indonesia</p>
<hr class="my-4">

<p class="h5">Profil:</p>
<a href="{% url 'profile' %}" class="btn btn-outline-primary" role="button">Profil Saya</a>
<a href="{% url 'logout' %}" class="btn btn-outline-primary" role="button">Logout</a>


<br><br><br>

<p class="h5">Kendaraan</p>
<a href="#" class="btn btn-outline-primary" role="button">List Kendaraan</a>

<br><br><br>

<p class="h5">Batch Pengiriman</p>
<a href="#" class="btn btn-outline-primary" role="button">List Batch Pengiriman</a>
<a href="#" class="btn btn-outline-primary" role="button">List Riwayat Status Batch Pengiriman</a>

{% endblock content %}

login/templates/dashboardPF.html
{% extends "base_template.html" %}

{% block content %}

<h1 class="display-4">Homepage Petugas Faskes</h1>
<p class="lead font-italic">SIDIA Indonesia</p>
<hr class="my-4">

<p class="h5">Profil:</p>
<a href="{% url 'profile' %}" class="btn btn-outline-primary" role="button">Profil Saya</a>
<a href="{% url 'logout' %}" class="btn btn-outline-primary" role="button">Logout</a>


<br><br><br>

<p class="h5">Permohonan Sumber Daya</p>
<a href="#" class="btn btn-outline-primary" role="button">Buat Permohonan Sumber Daya</a>
<a href="#" class="btn btn-outline-primary" role="button">List Permohonan Sumber Daya</a>
<a href="#" class="btn btn-outline-primary" role="button">List Riwayat Status Permohonan Sumber Daya</a>


<br><br><br>

<p class="h5">Fasilitas Kesehatan</p>
<a href="{% url 'listStokFaskes' %}" class="btn btn-outline-primary" role="button">List Stok Faskes</a>

<br><br><br>

<p class="h5">Warehouse Satgas</p>
<a href="#" class="btn btn-outline-primary" role="button">List Stok Warehouse Satgas</a>


<br><br><br>

<p class="h5">Batch Pengiriman</p>
<a href="#" class="btn btn-outline-primary" role="button">List Batch Pengiriman</a>


{% endblock content %}

login/templates/dashboardS.html
{% extends "base_template.html" %}

{% block content %}

<h1 class="display-4">Homepage Supplier</h1>
<p class="lead font-italic">SIDIA Indonesia</p>
<hr class="my-4">

<p class="h5">Profil:</p>
<a href="{% url 'profile' %}" class="btn btn-outline-primary" role="button">Profil Saya</a>
<a href="{% url 'logout' %}" class="btn btn-outline-primary" role="button">Logout</a>


<br><br><br>

<p class="h5">Item Sumber Daya</p>
<a href="#" class="btn btn-outline-primary" role="button">Buat Item Sumber Daya</a>
<a href="#" class="btn btn-outline-primary" role="button">List Item Sumber Daya</a>

<br><br><br>

<p class="h5">Pesanan Sumber Daya</p>
<a href="{% url 'psd6:listPSD' %}" class="btn btn-outline-primary" role="button">List Pesanan Sumber Daya</a>

<br><br><br>

<p class="h5">Fasilitas Kesehatan</p>
<a href="{% url 'faskes_5:readFaskesS' %}" class="btn btn-outline-primary" role="button">List Faskes</a>

<br><br><br>

<p class="h5">Warehouse</p>
<a href="{% url 'warehouseSatgas_5:readWarehouseSatgasS' %}" class="btn btn-outline-primary" role="button">List Warehouse Satgas</a>
<a href="#" class="btn btn-outline-primary" role="button">List Stok Warehouse Satgas</a>


{% endblock content %}

login/templates/home.html
{% extends "base_template.html" %}

{% block content %}

<h1 class="display-4">Welcome!</h1>
<p class="lead font-italic">SIDIA</p>
<hr class="my-4">

<a href="{% url 'login' %}" class="btn btn-outline-primary" role="button">Login</a>
<a href="{% url 'registerPilihan' %}" class="btn btn-outline-primary" role="button">Register</a>

{% endblock content %}

login/templates/login.html
{% extends "base_template.html" %}

{% block content %}

<style>
    input, select {
        display: block;
        width: 50%;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        color: #555;
        background-color: #fff;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
    }
</style>

<h1 class="display-4">Login</h1>
<p class="lead font-italic">SIDIA</p>
<hr class="my-4">

<div class="container"> 
    <small class="text-muted">{{ message }}</small> <br><br>  
       
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br><br> 
        <button class="btn btn-outline-primary" type="submit">Submit</button>
    </form>
</div>

{% endblock content %}

login/templates/registerPilihan.html
{% extends "base_template.html" %}
{% block content %}

<h1 class="display-4">Register as:</h1>
<p class="lead font-italic">SIDIA</p>
<hr class="my-4">

<a href="{% url 'regadminsatgas' %}" class="btn btn-outline-primary" role="button">Admin Satgas</a>
<a href="{% url 'regsupplier' %}" class="btn btn-outline-primary" role="button">Supplier</a>
<a href="{% url 'regpetugasdistribusi' %}" class="btn btn-outline-primary" role="button">Petugas Distribusi</a>
<a href="{% url 'regpetugasfaskes' %}" class="btn btn-outline-primary" role="button">Petugas Faskes</a>

{% endblock content %}