psd6/urls.py
from django.urls import path, include
from . import views

app_name = "psd6"
urlpatterns = [
    path('create', views.createPSD, name="createPSD"),
    path('getData', views.getData, name="getData"),
    path('list', views.listPSD, name="listPSD"),
    path('deleteDaftarItem/<nomorPesanan>/<noUrut>/', views.deleteDaftarItem, name="deleteDaftarItem"),
    path('delete/<nomorPesanan>/', views.deletePSD, name="deletePSD"),
    path('update/<nomorPesanan>/', views.updatePSD, name="updatePSD"),
    path('detail/<nomorPesanan>/', views.detailPSD, name="detailPSD"),
    path('tambahDaftarItem', views.tambahDaftarItem, name="tambahDaftarItem")
]

riwayatStatusPSD7/urls.py
from django.urls import path, include
from . import views

app_name = "riwayatStatusPSD7"
urlpatterns = [
    path('list/<nomorPesanan>', views.listRiwayatPSD, name="listRiwayatPSD"),
    path('create/<nomorPesanan>/<status>', views.createRiwayatPSD, name="createRiwayatPSD"),
    # path('', views.home, name="home"),
    # path('login', views.login, name="login"),
    # path('logout', views.logout, name="logout"),
    # path('registerPilihan', views.registerPilihan, name="registerPilihan"),
    # path('regadminsatgas', views.register_adminsatgas, name="regadminsatgas"),
    # path('regsupplier', views.register_supplier, name="regsupplier"),
    # path('regpetugasdistribusi', views.register_petugasdistribusi, name="regpetugasdistribusi"),
    # path('regpetugasfaskes', views.register_petugasfaskes, name="regpetugasfaskes"),
    # path('dashboard', views.dashboard, name="dashboard")
]

tk4a11/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('PSD/', include('psd6.urls')),
    path('RiwayatStatusPSD/', include('riwayatStatusPSD7.urls')),
    path('StokFaskes/', include('stockFaskes8.urls')),
    path('faskes_5/', include('faskes_5.urls')),
    path('warehouseSatgas_5/', include('warehouseSatgas_5.urls')),
    path('batchPengiriman_5/', include('batchPengiriman_5.urls')),

]

psd6/models.py
from django.db import models

# Create your models here.

psd6/forms.py
from django import forms
import datetime
from collections import namedtuple
from django.db import connection

# class createPSDForm(forms.Form):
#     cursor = connection.cursor()
#     cursor.execute("select distinct username, username from sidia.supplier")
#     supplier = forms.ChoiceField(choices = cursor.fetchall())
    
#     # cursor = connection.cursor()
#     # sql = "select kode from sidia.item_sumber_daya where username_supplier=" + "'" + supplier + "'"
#     # cursor.execute(sql)
#     # kode_item = forms.ChoiceField(choices = cursor.fetchall())

psd6/views.py
from django.shortcuts import render
from django.shortcuts import render, reverse, redirect
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.db import connection
from collections import namedtuple
import datetime

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def listPSD(request):
    print(request.session.keys())
    cursor = connection.cursor()
    cursor.execute("SET SEARCH_PATH TO SIDIA;")
    username = request.session['username']
    role = request.session['role']

    if role == "admin_satgas":
        cursor.execute("CREATE VIEW sqlTemp AS SELECT DISTINCT ON (nomor_pesanan) nomor_pesanan, username_admin_satgas, rsp.tanggal, total_berat, total_harga, total_item, kode_status_pesanan from pesanan_sumber_daya JOIN transaksi_sumber_daya tsd on nomor_pesanan=nomor JOIN riwayat_status_pesanan rsp ON nomor_pesanan=no_pesanan ORDER BY nomor_pesanan, rsp.tanggal DESC;")
        sqlListPSDView = "SELECT * FROM sqlTemp WHERE username_admin_satgas=%s"
        cursor.execute(sqlListPSDView, [username])
        listPSD = namedtuplefetchall(cursor)
        print(listPSD)
        cursor.execute("DROP VIEW sqlTemp")
        args = {"listPSD": listPSD} 
        return render(request, "listPSDAS.html", args)

    elif role == "supplier":
        cursor.execute("CREATE VIEW sqlTemp AS SELECT DISTINCT ON (nomor_pesanan) nomor_pesanan, username_admin_satgas, username_supplier, rsp.tanggal, total_berat, total_harga, total_item, kode_status_pesanan from pesanan_sumber_daya JOIN transaksi_sumber_daya tsd on nomor_pesanan=nomor JOIN riwayat_status_pesanan rsp ON nomor_pesanan=no_pesanan ORDER BY nomor_pesanan, rsp.tanggal DESC;")
        sqlListPSDView = "SELECT * FROM sqlTemp WHERE username_supplier=%s"
        cursor.execute(sqlListPSDView, [username])
        listPSD = namedtuplefetchall(cursor)
        print(listPSD)
        cursor.execute("DROP VIEW sqlTemp")
        args = {"listPSD": listPSD}             
        return render(request, "listPSDSup.html", args)
        
    else:
        pass
    

def getData(request):
    cursor = connection.cursor()
    if request.method == 'GET':
        selectedSupplier = request.GET.get('supplier')
        print(selectedSupplier)
        sqlKode = "SELECT kode FROM sidia.item_sumber_daya WHERE username_supplier=" + "'" + selectedSupplier + "';"
   
    kodeItemListTemp = cursor.execute(sqlKode)
    kodeItemList = namedtuplefetchall(cursor)
    kodeItemListFinal = []
    for kode in kodeItemList:
        kodeItemListFinal.append(kode.kode)
    print(kodeItemListFinal)

    args = {"kodeItemList": kodeItemListFinal, "selectedSupplier" : selectedSupplier} 
    return JsonResponse(args)

def tambahDaftarItem(request):
    cursor = connection.cursor()
    if request.method == 'GET':
        kodeItem = request.GET.get('kodeItem')
        sql = "SELECT harga_satuan FROM sidia.item_sumber_daya WHERE kode=" + "'" + kodeItem + "';"
   
    cursor.execute(sql)
    hargaSatuan = namedtuplefetchall(cursor)

    cursor.execute("SELECT nama FROM sidia.item_sumber_daya WHERE kode=" + "'" + kodeItem + "';")
    namaItem = namedtuplefetchall(cursor)

    args = {"hargaSatuan": hargaSatuan, 'namaItem' : namaItem}
    return JsonResponse(args)

def createPSD(request):
    usernameAdmin = request.session['username']
    cursor = connection.cursor()
    if request.method =='POST':
        noTransaksiForm = request.POST.get("noTransaksiForm")
        petugasForm = request.POST.get("petugasForm")
        supplierForm = request.POST.get("supplierForm")
        daftarItem = request.POST.getlist("daftarItem[]")
        tanggal = datetime.datetime.now()

        # sqlTransaksiSumberDaya = "INSERT INTO sidia.transaksi_sumber_daya (tanggal) VALUES (%s);"
        sqlTransaksiSumberDaya = "INSERT INTO sidia.transaksi_sumber_daya VALUES (%s, %s);"
        cursor.execute(sqlTransaksiSumberDaya, [noTransaksiForm, str(tanggal)])
        # cursor.execute("SELECT LASTVAL() FROM sidia.transaksi_sumber_daya;")
        # noTransaksiForm = namedtuplefetchall(cursor)
        # print(noTransaksiForm)

        sqlDaftarItem = "INSERT INTO sidia.daftar_item VALUES (%s, %s, %s, %s)"
        for i in range(0, len(daftarItem), 3):
            cursor.execute(sqlDaftarItem, (noTransaksiForm, daftarItem[i], daftarItem[i+1], daftarItem[i+2]))
        
        # sqlHargaSatuan = "SELECT harga_kumulatif FROM sidia.daftar_item WHERE no_transaksi_sumber_daya=%s"
        # cursor.execute(sqlHargaSatuan, [noTransaksiForm])
        # hargaSatuanTemp = namedtuplefetchall(cursor)
        # hargaTotal = 0
        # for i in range(0, len(hargaSatuanTemp)):
        #     hargaTotal += hargaSatuanTemp[i].harga_kumulatif
        # print(hargaSatuanTemp)
        # print(hargaTotal)

        sqlPesananSumberDaya = "INSERT INTO sidia.pesanan_sumber_daya VALUES (%s, %s);"
        cursor.execute(sqlPesananSumberDaya, [noTransaksiForm, usernameAdmin])

        sqlRiwayatStatusPesanan = "INSERT INTO sidia.RIWAYAT_STATUS_PESANAN VALUES (%s, %s, %s, %s);"
        cursor.execute(sqlRiwayatStatusPesanan, ["REQ-SUP", noTransaksiForm, supplierForm, str(tanggal)])
        return redirect('psd6:listPSD')


    noTransaksi = cursor.execute("SELECT MAX(nomor) FROM sidia.transaksi_sumber_daya;")
    noTransaksiTemp = namedtuplefetchall(cursor)
    noTransaksiInt = noTransaksiTemp[0].max + 1

    supplierListTemp = cursor.execute("SELECT DISTINCT username FROM sidia.supplier;")
    supplierList = namedtuplefetchall(cursor)

    args = {"noTransaksi": noTransaksiInt, "petugasCurrent": usernameAdmin, "supplierList" : supplierList}
    return render(request, "createPSD.html", args)

def deletePSD(request, nomorPesanan):
    cursor = connection.cursor()
    cursor.execute("set search_path to sidia")
    cursor.execute("delete from transaksi_sumber_daya where nomor = '" + nomorPesanan + "'")
    cursor.execute("delete from pesanan_sumber_daya where nomor_pesanan = '" + nomorPesanan + "'")
    cursor.execute("delete from daftar_item where no_transaksi_sumber_daya = '" + nomorPesanan + "'")
    cursor.execute("delete from riwayat_status_pesanan where no_pesanan = '" + nomorPesanan + "'")
    return redirect('psd6:listPSD')

def updatePSD(request, nomorPesanan):
    usernameAdmin = request.session['username']
    cursor = connection.cursor()
    cursor.execute("set search_path to sidia")
    if request.method =='POST':
        noTransaksiForm = request.POST.get("noTransaksiForm")
        petugasForm = request.POST.get("petugasForm")
        supplierForm = request.POST.get("supplierForm")
        daftarItem = request.POST.getlist("daftarItem[]")
        yangDiDelete = request.POST.getlist("yangDiDelete[]")
        tanggal = datetime.datetime.now()

        sqlDaftarItem = "INSERT INTO sidia.daftar_item VALUES (%s, %s, %s, %s)"
        sqlRetriveKode = "SELECT kode_item_sumber_daya, no_urut FROM daftar_item WHERE no_transaksi_sumber_daya =%s"
        cursor.execute(sqlRetriveKode, [noTransaksiForm])
        kodeUdahAda = namedtuplefetchall(cursor)

        for i in range(0, len(daftarItem), 3):
            cursor.execute(sqlDaftarItem, (noTransaksiForm, daftarItem[i], daftarItem[i+1], daftarItem[i+2]))
        
        sqlDelete = "DELETE from daftar_item where no_transaksi_sumber_daya=%s AND kode_item_sumber_daya =%s AND no_urut=%s;"
        for i in range(0, len(yangDiDelete), 2):
            cursor.execute(sqlDelete, [noTransaksiForm, yangDiDelete[i], yangDiDelete[i+1]])

        # sqlHargaSatuan = "SELECT harga_kumulatif FROM sidia.daftar_item WHERE no_transaksi_sumber_daya=%s"
        # cursor.execute(sqlHargaSatuan, [noTransaksiForm])
        # hargaSatuanTemp = namedtuplefetchall(cursor)

        # hargaTotal = 0
        # for i in range(0, len(hargaSatuanTemp)):
        #     hargaTotal += hargaSatuanTemp[i].harga_kumulatif
        # print(hargaSatuanTemp)
        # print(hargaTotal)

        # sqlPesananSumberDaya = "UPDATE sidia.pesanan_sumber_daya SET total_harga=%s;"
        # cursor.execute(sqlPesananSumberDaya, [hargaTotal])

        # sqlRiwayatStatusPesanan = "UPDATE sidia.RIWAYAT_STATUS_PESANAN SET tanggal=%s;"
        # cursor.execute(sqlRiwayatStatusPesanan, [str(tanggal)])

        sqlTransaksiSumberDaya = "UPDATE sidia.transaksi_sumber_daya SET tanggal=%s;"
        cursor.execute(sqlTransaksiSumberDaya, [str(tanggal)])

        return redirect('psd6:listPSD')

    cursor.execute("SELECT username_supplier from daftar_item di JOIN pesanan_sumber_daya psd ON no_transaksi_sumber_daya=nomor_pesanan JOIN item_sumber_daya isd ON kode_item_sumber_daya=kode JOIN transaksi_sumber_daya tsd on no_transaksi_sumber_daya=nomor WHERE nomor_pesanan=%s", [nomorPesanan])
    supplier = namedtuplefetchall(cursor)

    cursor.execute("SELECT kode, psd.nomor_pesanan, username_admin_satgas, tsd.tanggal, username_supplier, di.no_urut, isd.nama, isd.harga_satuan, di.jumlah_item, psd.total_harga from daftar_item di JOIN pesanan_sumber_daya psd ON no_transaksi_sumber_daya=nomor_pesanan JOIN item_sumber_daya isd ON kode_item_sumber_daya=kode JOIN transaksi_sumber_daya tsd on no_transaksi_sumber_daya=nomor WHERE nomor_pesanan=%s", [nomorPesanan])
    daftarItemList = namedtuplefetchall(cursor)
    cursor.execute("SELECT COUNT(*) from daftar_item WHERE no_transaksi_sumber_daya=%s", [nomorPesanan])
    noUrutMulaiDariSini = namedtuplefetchall(cursor)

    cursor.execute("SELECT kode FROM sidia.item_sumber_daya WHERE username_supplier=" + "'" + supplier[0].username_supplier + "';")
    kodeItemList = namedtuplefetchall(cursor)
    

psd6/templates/detail.html
{% extends 'base_template.html' %}
{% load static %}
{% block title %} Detail {% endblock %}

{% block content %}

<style>
    input, select {
        display: block;
        width: 100%;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        color: #555;
        background-color: #f9f9f9;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
    }
</style>

<div class="container col-lg-12">  
    {% for item in detailPSD %}
    <h1 class="display-4">Detail Pesanan Sumber Daya {{ item.nomor_pesanan }}</h1>
    <hr class="my-4">
    <div class=col-lg-6>
        <div class=col-lg-12>
        <label>Nomor Transaksi: </label>
            <input type="text" name="noTransaksiForm" value="TOR{{item.nomor_pesanan}}" disabled>

        <label>Petugas: </label>
            <input type="text"name="petugasForm" value="{{item.username_admin_satgas}}" disabled>
        
        <label>Tanggal: </label>
            <input type="text" name="noTransaksiForm" value="{{item.tanggal}}" disabled>

        <label>Supplier: </label>
            <input type="text" name="petugasForm" value="{{item.username_supplier}}" disabled>
        </div>
    </div>
    {% endfor %}
    <div class=col-lg-6>
        <br>
        <table class="table table-striped table table-hover">
            <thead>
                <tr>
                    <th scope="col">No Urut</th>
                    <th scope="col">Item</th>
                    <th scope="col">Harga Satuan</th>
                    <th scope="col">Jumlah Item</th>
                </tr>
            </thead>
            <tbody>
                {% for item in detailDaftarItem %}
                <tr>
                    <td>{{item.no_urut}}</td>
                    <td>{{item.nama}}</td>
                    <td>{{item.harga_satuan}}</td>
                    <td>{{item.jumlah_item}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <label>Total Harga: </label>
            <input type="text"name="totalHarga" value="{{totalHarga}}" disabled>
    </div>
    <br><br>
    <a href="{% url 'psd6:listPSD' %}" role="button" class="btn btn-outline-primary" style="float: left;">Kembali</a>

</div>


{% endblock content %}

psd6/templates/listPSDAS.html
{% extends "base_template.html" %}
{% block content %}

<style>
    input, select {
        display: block;
        width: 50%;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        color: #555;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
    }
</style>

<div class="container col-lg-12">  
  <h1 class="display-4">List Pesanan Sumber Daya</h1>
  <hr class="my-4">
  <div class=col-lg-12>
      <table class="table table-striped table table-hover" style="text-align: center;"> 
          <thead>
              <tr style="text-align: center;">
                <th scope="col">No. Transaksi</th>
                <th scope="col">Petugas Satgas</th>
                <th scope="col">Tanggal</th>
                <th scope="col">Total Berat</th>
                <th scope="col">Total Item</th>
                <th scope="col">Total Harga</th>
                <th scope="col">Status</th>
                <th scope="col" style="text-align: center;">Action</th>
              </tr>
          </thead>
          <tbody id=tableDaftarItem>
            {% for item in listPSD %}
            <tr>
              <td>TOR{{ item.nomor_pesanan}}</td>
              <td>{{ item.username_admin_satgas}}</td>
              <td>{{ item.tanggal}}</td>
              <td>{{ item.total_berat}}</td>
              <td>{{ item.total_item}}</td>
              <td>{{ item.total_harga}}</td>
              <td>{{ item.kode_status_pesanan}}</td>
              <td>
                <a href="{% url 'psd6:detailPSD' item.nomor_pesanan %}" class="btn btn-outline-primary" role="button">Detail</a>
                <a href="{% url 'riwayatStatusPSD7:listRiwayatPSD' item.nomor_pesanan %}" class="btn btn-outline-primary" role="button">Riwayat Status</a>
                {% if item.kode_status_pesanan == "REQ-SUP" %}
                <a href="{% url 'psd6:updatePSD' item.nomor_pesanan %}" class="btn btn-outline-primary" role="button">Update</a>
                <a href="{% url 'psd6:deletePSD' item.nomor_pesanan %}" class="deleteButton btn btn-outline-primary" role="button">Delete</a>
                {% endif %}
              </td>
            </tr>
            {% endfor %}
      
          </tbody>
      </table>
  </div>
  </div>

</div>
<script>
  $(document).ready(function (){
    $("body").on("click", ".deleteButton", function() {
      alert("Data berhasil dihapus");
    });
  });
  </script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  
{% endblock content %}

psd6/templates/listPSDSup.html
{% extends "base_template.html" %}
{% block content %}

<style>
    input, select {
        display: block;
        width: 50%;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        color: #555;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
    }
</style>

<div class="container col-lg-12">  
  <h1 class="display-4">List Pesanan Sumber Daya</h1>
  <hr class="my-4">
  <div class=col-lg-12>
      <table class="table table-striped table table-hover"> 
          <thead>
              <tr >
                <th scope="col">No. Transaksi</th>
                <th scope="col">Petugas Satgas</th>
                <th scope="col">Tanggal</th>
                <th scope="col">Total Berat</th>
                <th scope="col">Total Item</th>
                <th scope="col">Total Harga</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
              </tr>
          </thead>
          <tbody id=tableDaftarItem>
            {% for item in listPSD %}
            <tr>
              <td>TOR{{ item.nomor_pesanan}}</td>
              <td>{{ item.username_admin_satgas}}</td>
              <td>{{ item.tanggal}}</td>
              <td>{{ item.total_berat}}</td>
              <td>{{ item.total_item}}</td>
              <td>{{ item.total_harga}}</td>
              <td class="kodeStatus" id="kodeStatus{{ item.nomor_pesanan}}">{{ item.kode_status_pesanan }}</td>
              <td>
                <a href="{% url 'psd6:detailPSD' item.nomor_pesanan %}" class="btn btn-outline-primary" role="button">Detail</a>
                <a href="{% url 'riwayatStatusPSD7:listRiwayatPSD' item.nomor_pesanan %}" class="btn btn-outline-primary" role="button">Riwayat Status</a>
                {% if item.kode_status_pesanan == "REQ-SUP" %}
                  <a href="{%  url 'riwayatStatusPSD7:createRiwayatPSD' item.nomor_pesanan 'REJ-SUP' %}" class="updateButton btn btn-outline-primary btn-xs" role="button">Reject</a>
                  <a href="{%  url 'riwayatStatusPSD7:createRiwayatPSD' item.nomor_pesanan 'PRO-SUP' %}" class="updateButton btn btn-outline-primary btn-xs" role="button">Process</a>
                {% endif %}
                {% if item.kode_status_pesanan == "PRO-SUP" %}
                  <a href="{%  url 'riwayatStatusPSD7:createRiwayatPSD' item.nomor_pesanan 'MAS-SUP' %}" class="updateButton btn btn-outline-primary btn-xs" role="button">Selesai dengan 
                    Masalah</a>
                  <a href="{%  url 'riwayatStatusPSD7:createRiwayatPSD' item.nomor_pesanan 'FIN-SUP' %}" class="updateButton btn btn-outline-primary btn-xs" role="button">Selesai</a>
                {% endif %}
              </td>
            </tr>
            {% endfor %}  
          </tbody>
      </table>
  </div>
  </div>
</div>
<script>
  $(document).ready(function (){
    $("body").on("click", ".updateButton", function() {
      alert("Status untuk pesanan berhasil dibuat");
    });
  });
  </script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

{% endblock content %}