faskes_5/urls.py
from django.urls import path
from .views import create_faskes, ajaxLokasiFaskes, ajaxTipeFaskes, read_faskes, delete_faskes, update_faskes
app_name = 'faskes_5'

urlpatterns = [
    path('createFaskes/', create_faskes, name='createFaskes'),
    path('ajaxLokasiFaskes/', ajaxLokasiFaskes, name='ajaxLokasiFaskes'),
    path('ajaxTipeFaskes/', ajaxTipeFaskes, name='ajaxTipeFaskes'),
    path('readFaskes/', read_faskes, name='readFaskes'),
    path('readFaskesS/', read_faskes, name='readFaskesS'),
    path('deleteFaskes/', delete_faskes, name='deleteFaskes'),
    path('updateFaskes/', update_faskes, name='updateFaskes'),

]

psd6/urls.py
from django.urls import path, include
from . import views

app_name = "psd6"
urlpatterns = [
    path('create', views.createPSD, name="createPSD"),
    path('getData', views.getData, name="getData"),
    path('list', views.listPSD, name="listPSD"),
    path('deleteDaftarItem/<nomorPesanan>/<noUrut>/', views.deleteDaftarItem, name="deleteDaftarItem"),
    path('delete/<nomorPesanan>/', views.deletePSD, name="deletePSD"),
    path('update/<nomorPesanan>/', views.updatePSD, name="updatePSD"),
    path('detail/<nomorPesanan>/', views.detailPSD, name="detailPSD"),
    path('tambahDaftarItem', views.tambahDaftarItem, name="tambahDaftarItem")
]

tk4a11/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('PSD/', include('psd6.urls')),
    path('RiwayatStatusPSD/', include('riwayatStatusPSD7.urls')),
    path('StokFaskes/', include('stockFaskes8.urls')),
    path('faskes_5/', include('faskes_5.urls')),
    path('warehouseSatgas_5/', include('warehouseSatgas_5.urls')),
    path('batchPengiriman_5/', include('batchPengiriman_5.urls')),

]

faskes_5/models.py
from django.db import models

# Create your models here.

faskes_5/forms.py
from django import forms
import datetime
from collections import namedtuple
from django.db import connection


class CreateFaskesForm(forms.Form):
    kode_faskes = forms.CharField(label='Kode Faskes', max_length=50)
    
    id_Lokasi_list = []
    id_lokasi = forms.ChoiceField(choices=id_Lokasi_list, required=True)
    
    lokasi = forms.CharField(label=("Lokasi"), required=True, max_length=50)

    petugas_faskes_list = []
    petugas_faskes = forms.ChoiceField(choices=petugas_faskes_list, required=True)
    
    
    kode_tipe_faskes_list = []
    kode_tipe_faskes = forms.ChoiceField(choices=kode_tipe_faskes_list, required=True)
    
    tipe_faskes = forms.CharField(label=("Tipe Faskes"), required=True, max_length=50)


    def __init__(self, *args, **kwargs):
        super(CreateFaskesForm, self).__init__(*args, **kwargs)
        with connection.cursor() as cursor:
            cursor.execute("SELECT ID, ID FROM SIDIA.LOKASI")
            self.fields['id_lokasi'].choices = cursor.fetchall()
            cursor.execute("SELECT USERNAME, USERNAME FROM SIDIA.PETUGAS_FASKES")
            self.fields['petugas_faskes'].choices = cursor.fetchall()
            cursor.execute("SELECT KODE, KODE FROM SIDIA.TIPE_FASKES")
            self.fields['kode_tipe_faskes'].choices = cursor.fetchall()
    
            self.fields['id_lokasi'].widget.attrs = {'id': 'id_lokasi'}
            self.fields['lokasi'].widget.attrs = {'id': 'lokasi'}
            self.fields['kode_tipe_faskes'].widget.attrs = {'id': 'kode_tipe_faskes'}
            self.fields['tipe_faskes'].widget.attrs = {'id': 'tipe_faskes'}


class UpdateFaskesForm(forms.Form):
    kode_faskes_nasional = forms.CharField(label='Kode Faskes', max_length=50)
    
    id_lokasi_list = []
    id_lokasi = forms.ChoiceField(choices=id_lokasi_list, required=True)
    
    lokasi = forms.CharField(label=("Lokasi"), required=True, max_length=50)

    petugas_faskes_list = []
    petugas_faskes = forms.ChoiceField(choices=petugas_faskes_list, required=True)
    
    kode_tipe_faskes_list = []
    kode_tipe_faskes = forms.ChoiceField(choices=kode_tipe_faskes_list, required=True)
    
    tipe_faskes = forms.CharField(label=("Tipe Faskes"), required=True, max_length=50)


    def __init__(self, *args, **kwargs):
        super(UpdateFaskesForm, self).__init__(*args, **kwargs)
        with connection.cursor() as cursor:
            self.fields['kode_faskes_nasional'].widget.attrs['readonly'] = True
            self.fields['kode_faskes_nasional'].widget.attrs['class'] = 'disabled'
            cursor.execute("SELECT ID, ID FROM SIDIA.LOKASI")
            self.fields['id_lokasi'].choices = cursor.fetchall()
            self.fields['id_lokasi'].widget.attrs = {'id': 'id_lokasi'}
            cursor.execute("SELECT USERNAME, USERNAME FROM SIDIA.PETUGAS_FASKES")
            self.fields['petugas_faskes'].choices = cursor.fetchall()
            cursor.execute("SELECT KODE, KODE FROM SIDIA.TIPE_FASKES")
            self.fields['kode_tipe_faskes'].choices = cursor.fetchall()
            self.fields['lokasi'].widget.attrs['readonly'] = True
            self.fields['lokasi'].widget.attrs = {'id': 'lokasi'}
            self.fields['tipe_faskes'].widget.attrs['readonly'] = True
            self.fields['tipe_faskes'].widget.attrs = {'id': 'tipe_faskes'}
            self.fields['kode_tipe_faskes'].widget.attrs = {'id': 'kode_tipe_faskes'}

faskes_5/views.py
from django.shortcuts import render
from django.core import serializers
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import *
from django.db import connection
from datetime import datetime
from django.contrib import messages


def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def ajaxLokasiFaskes(request):
    id_lokasi = request.GET.get('id_lokasi')
    print(id_lokasi)
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT JALAN_NO,KELURAHAN,KECAMATAN,KABKOT,PROVINSI FROM SIDIA.LOKASI WHERE ID = %s", [id_lokasi])
        data = cursor.fetchall()
    list_lokasi = []
    for i in data[0]:
        list_lokasi.append(i)

    return JsonResponse({'id': list_lokasi})

def ajaxTipeFaskes(request):
    kode_tipe_faskes = request.GET.get('kode_tipe_faskes')
    print(kode_tipe_faskes)
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT NAMA_TIPE FROM SIDIA.TIPE_FASKES WHERE KODE = %s", [kode_tipe_faskes])
        data = cursor.fetchall()
    list_tipe_faskes = []
    for i in data[0]:
        list_tipe_faskes.append(i)

    return JsonResponse({'id': list_tipe_faskes})



def create_faskes(request):
    form = CreateFaskesForm()
    if request.method == "POST":
        kode_faskes = request.POST['kode_faskes']
        id_lokasi = request.POST['id_lokasi']
        lokasi = request.POST['lokasi']
        petugas_faskes = request.POST['petugas_faskes']
        kode_tipe_faskes = request.POST['kode_tipe_faskes']
        tipe_faskes = request.POST['tipe_faskes']

        data_baru = [kode_faskes, id_lokasi, petugas_faskes, kode_tipe_faskes]
        print(data_baru)
        with connection.cursor() as cursor:
            cursor.execute(
                'INSERT INTO SIDIA.FASKES VALUES (%s, %s, %s, %s)', data_baru)
        return redirect('faskes_5:readFaskes')
    return render(request, 'createFaskes.html', {'form': form})


def read_faskes(request):
    role = request.session['role']
    if role == "admin_satgas":
        with connection.cursor() as cursor:
            cursor.execute("SET SEARCH_PATH TO SIDIA;")
            sql = "SELECT DISTINCT kode_faskes_nasional,JALAN_NO,KELURAHAN,KECAMATAN,KABKOT,PROVINSI, nama_tipe, username_petugas from faskes JOIN lokasi on id_lokasi=id JOIN tipe_faskes on kode_tipe_faskes=kode;"
            cursor.execute(sql)
            result = dictfetchall(cursor)
        return render(request, 'readFaskes.html', {'form': result})
    elif role == "supplier":
        with connection.cursor() as cursor:
            cursor.execute("SET SEARCH_PATH TO SIDIA;")
            sql = "SELECT DISTINCT kode_faskes_nasional,JALAN_NO,KELURAHAN,KECAMATAN,KABKOT,PROVINSI, nama_tipe, username_petugas from faskes JOIN lokasi on id_lokasi=id JOIN tipe_faskes on kode_tipe_faskes=kode;"
            cursor.execute(sql)
            result = dictfetchall(cursor)
        return render(request, 'readFaskesS.html', {'form': result})
    else:
        pass


def delete_faskes(request):
    role = request.session['role']
    print(role)
    if role != 'admin_satgas':
        return redirect('home')
    if request.method == 'GET':
        if request.GET.get('kode_faskes_nasional') is not None:
            kode_faskes_nasional = request.GET.get('kode_faskes_nasional')
            with connection.cursor() as cursor:
                cursor.execute("DELETE FROM SIDIA.FASKES WHERE kode_faskes_nasional = %s", [kode_faskes_nasional])
                messages.success(request, ('Data berhasil dihapus'))

    return HttpResponseRedirect(reverse('faskes_5:readFaskes'))

def update_faskes(request):
    role = request.session['role']
    print(role)
    if role != 'admin_satgas':
        return redirect('home')
    if request.method == 'GET':
        print(request.GET.get('kode_faskes_nasional'))
        if request.GET.get('kode_faskes_nasional') is not None:
            kode_faskes_nasional = request.GET.get('kode_faskes_nasional')

            with connection.cursor() as cursor:
                cursor.execute("SELECT kode_faskes_nasional, id_lokasi,jalan_no,kelurahan,kecamatan,kabkot,provinsi,username_petugas,kode_tipe_faskes, nama_tipe FROM SIDIA.FASKES JOIN SIDIA.LOKASI ON ID = ID_LOKASI JOIN SIDIA.TIPE_FASKES ON KODE_TIPE_FASKES = KODE WHERE KODE_FASKES_NASIONAL = %s", [kode_faskes_nasional])
                result = dictfetchall(cursor)
            data_faskes = {}
            data_faskes['kode_faskes_nasional'] = result[0]['kode_faskes_nasional']
            data_faskes['id_lokasi'] = result[0]['id_lokasi']
            data_faskes['petugas_faskes'] = result[0]['username_petugas']
            data_faskes['lokasi'] = result[0]['jalan_no'],result[0]['kecamatan'], result[0]['kelurahan'],result[0]['kabkot']
            data_faskes['kode_tipe_faskes'] = result[0]['kode_tipe_faskes']
            data_faskes['tipe_faskes'] = result[0]['nama_tipe']
            form = UpdateFaskesForm(initial=data_faskes)
    else:
        kode_faskes_nasional = request.POST['kode_faskes_nasional']
        id_lokasi = request.POST['id_lokasi']
        petugas_faskes = request.POST['petugas_faskes']
        lokasi = request.POST['lokasi']
        kode_tipe_faskes = request.POST['kode_tipe_faskes'] 
        tipe_faskes = request.POST['tipe_faskes'] 

        data_update = [id_lokasi,petugas_faskes,kode_tipe_faskes,kode_faskes_nasional]
        with connection.cursor() as cursor:
            cursor.execute("UPDATE SIDIA.FASKES SET ID_LOKASI =%s, USERNAME_PETUGAS = %s,KODE_TIPE_FASKES = %s WHERE KODE_FASKES_NASIONAL = %s", data_update)
        return redirect('faskes_5:readFaskes')
    return render(request, 'updateFaskes.html', {'form': form})

faskes_5/templates/createFaskes.html
{% extends "base_template.html" %}

{% block content %}

<style>
    input, select {
        display: block;
        width: 50%;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        color: #555;
        background-color: #fff;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
    }
</style>
<div class="container"> 
{% if request.session.role == 'admin_satgas' %} 
    <h1 class="display-4">Form Tambah Fasilitas Kesehatan</h1>
    <small class="text-muted">{{ message }}</small> <br><br> 
<hr class="my-4">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-outline-primary" type="submit">Simpan</button>
    </form>
{% else %}
        <h3>Harus Login dahulu sebagai Admin Satgas</h3>
        <a href="{% url 'login' %}">
            <button>
                Login
            </button>
        </a>
{% endif %} 
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $.ajax({
            type: 'GET',
            url: "{% url 'faskes_5:ajaxLokasiFaskes' %}",
            data: {
                id_lokasi: $('#id_lokasi').val()
            },
            async: false,
            success: function (response) {
                let res=''
                response.id.map((e) => {
                    res += e + ' , ';
                })
                $('#lokasi').val(res)
                $('#lokasi').prop('readonly',true)
            }
        });
        $('#id_lokasi').on('change', function () {
            $('#lokasi').val('')
            $.ajax({
                type: 'GET',
                url: "{% url 'faskes_5:ajaxLokasiFaskes' %}",
                data: {
                    id_lokasi: $('#id_lokasi').val()
                },
                async: false,
                success: function (response) {
                    let res=''
                    response.id.map((e) => {
                    res += e + ' , ';
                    })
                    $('#lokasi').val(res)
                    $('#lokasi').prop('readonly',true)
                }
            });
        });

        $.ajax({
            type: 'GET',
            url: "{% url 'faskes_5:ajaxTipeFaskes' %}",
            data: {
                kode_tipe_faskes: $('#kode_tipe_faskes').val()
            },
            async: false,
            success: function (response) {
                let res=''
                response.id.map((e) => {
                    res += e + '  ';
                })
                $('#tipe_faskes').val(res)
                $('#tipe_faskes').prop('readonly',true)
            }
        });
        $('#kode_tipe_faskes').on('change', function () {
            $('#tipe_faskes').val('')
            $.ajax({
                type: 'GET',
                url: "{% url 'faskes_5:ajaxTipeFaskes' %}",
                data: {
                    kode_tipe_faskes: $('#kode_tipe_faskes').val()
                },
                async: false,
                success: function (response) {
                    let res=''
                    response.id.map((e) => {
                    res += e + '  ';
                    })
                    $('#tipe_faskes').val(res)
                    $('#tipe_faskes').prop('readonly',true)
                }
            });
        });

    })
</script>
{% endblock content %}

faskes_5/templates/readFaskes.html
{% extends "base_template.html" %}
{% block content %}

<style>
    input, select {
        display: block;
        width: 50%;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        color: #555;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
    }
</style>

<div class="container col-lg-12">  
  <h1 class="display-4">List Fasilitas Kesehatan</h1>
  <hr class="my-4">
  <div class=col-lg-12>
      {% if messages %}
    <div>
        {% for message in messages %}
            <h5 class="{{message.tag}}">{{ message.message }}</h5>
        {% endfor %}
    </div>
    {% endif %}

      <table class="table table-striped table table-hover" style="text-align: center;"> 
          <thead>
              <tr style="text-align: center;">
                <th scope="col">Kode Faskes Nasional</th>
                <th scope="col">Lokasi</th>
                <th scope="col">Petugas Faskes</th>
                <th scope="col">Tipe Faskes</th>
              </tr>

          </thead>
          <tbody>
            {% for item in form %}
            <tr>
              <td>{{ item.kode_faskes_nasional}}</td>
              <td>{{ item.jalan_no}} {{ item.kelurahan}} {{ item.kecamatan}} </td>
              <td>{{ item.username_petugas}}</td>
              <td>{{ item.nama_tipe}}</td>

                <td>
                  <form action="{% url 'faskes_5:updateFaskes' %}" method="get">
                      <input type="hidden" id="kode_faskes_nasional" name="kode_faskes_nasional" value="{{ item.kode_faskes_nasional }}">
                      <button type="submit" class="btn btn-outline-primary">Update</button>
                  </form>
                </td>
                <td>
                  <form action="{% url 'faskes_5:deleteFaskes' %}" method="get">
                      <input type="hidden" id="kode_faskes_nasional" name="kode_faskes_nasional" value="{{ item.kode_faskes_nasional }}">
                      <button type="submit" class="btn btn-outline-primary">Delete</button>
                  </form>
                </td>
            </tr>
            {% endfor %}
      
          </tbody>
      </table>
  </div>
  </div>

</div>
{% endblock content %}

faskes_5/templates/readFaskesS.html
{% extends "base_template.html" %}
{% block content %}

<style>
    input, select {
        display: block;
        width: 50%;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        color: #555;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
    }
</style>

<div class="container col-lg-12">  
  <h1 class="display-4">List Fasilitas Kesehatan</h1>
  <hr class="my-4">
  <div class=col-lg-12>
      {% if messages %}
    <div>
        {% for message in messages %}
            <h5 class="{{message.tag}}">{{ message.message }}</h5>
        {% endfor %}
    </div>
    {% endif %}

      <table class="table table-striped table table-hover" style="text-align: center;"> 
          <thead>
              <tr style="text-align: center;">
                <th scope="col">Kode Faskes Nasional</th>
                <th scope="col">Lokasi</th>
                <th scope="col">Petugas Faskes</th>
                <th scope="col">Tipe Faskes</th>
              </tr>

          </thead>
          <tbody>
            {% for item in form %}
            <tr>
              <td>{{ item.kode_faskes_nasional}}</td>
              <td>{{ item.jalan_no}} {{ item.kelurahan}} {{ item.kecamatan}} </td>
              <td>{{ item.username_petugas}}</td>
              <td>{{ item.nama_tipe}}</td>
            </tr>
            {% endfor %}
      
          </tbody>
      </table>
  </div>
  </div>

</div>
{% endblock content %}

faskes_5/templates/updateFaskes.html
{% extends "base_template.html" %}

{% block content %}

<style>
    input, select {
        display: block;
        width: 50%;
        height: 34px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        color: #555;
        background-color: #fff;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
    }
</style>
<div class="container">  
    <h1 class="display-4">Form Ubah Fasilitas Kesehatan</h1>
    <small class="text-muted">{{ message }}</small> <br><br> 
<hr class="my-4">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-outline-primary" type="submit">Simpan</button>
    </form>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $.ajax({
            type: 'GET',
            url: "{% url 'faskes_5:ajaxLokasiFaskes' %}",
            data: {
                id_lokasi: $('#id_lokasi').val()
            },
            async: false,
            success: function (response) {
                let res=''
                response.id.map((e) => {
                    res += e + ' , ';
                })
                $('#lokasi').val(res)
                $('#lokasi').prop('readonly',true)
            }
        });
        $('#id_lokasi').on('change', function () {
            $('#lokasi').val('')
            $.ajax({
                type: 'GET',
                url: "{% url 'faskes_5:ajaxLokasiFaskes' %}",
                data: {
                    id_lokasi: $('#id_lokasi').val()
                },
                async: false,
                success: function (response) {
                    let res=''
                    response.id.map((e) => {
                    res += e + ' , ';
                    })
                    $('#lokasi').val(res)
                    $('#lokasi').prop('readonly',true)
                }
            });
        });

        $.ajax({
            type: 'GET',
            url: "{% url 'faskes_5:ajaxTipeFaskes' %}",
            data: {
                kode_tipe_faskes: $('#kode_tipe_faskes').val()
            },
            async: false,
            success: function (response) {
                let res=''
                response.id.map((e) => {
                    res += e + '  ';
                })
                $('#tipe_faskes').val(res)
                $('#tipe_faskes').prop('readonly',true)
            }
        });
        $('#kode_tipe_faskes').on('change', function () {
            $('#tipe_faskes').val('')
            $.ajax({
                type: 'GET',
                url: "{% url 'faskes_5:ajaxTipeFaskes' %}",
                data: {
                    kode_tipe_faskes: $('#kode_tipe_faskes').val()
                },
                async: false,
                success: function (response) {
                    let res=''
                    response.id.map((e) => {
                    res += e + '  ';
                    })
                    $('#tipe_faskes').val(res)
                    $('#tipe_faskes').prop('readonly',true)
                }
            });
        });

    })
</script>
{% endblock content %}